#Lang

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
    autocmd FileType python setlocal completeopt-=preview
    let g:jedi#use_tabs_not_buffers = 1
    let g:jedi#popup_on_dot = 0
'''

[[plugins]]
repo = 'ervandew/supertab'
on_ft = 'python'
hook_add = '''
    let g:SuperTabContextDefaultCompletionType = "context"
    let g:SuperTabDefaultCompletionType = "<c-n>"
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = 'python'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'
on_ft = ['c']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
